name: Release Changelog

on:
  push:
    branches:
      - main2

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create a release
        if: startsWith(github.event.head_commit.message, 'chore(release)')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body_path: ./CHANGELOG.md
